package migrate

import (
	"encoding/base64"
	"encoding/json"

	ycrdt "github.com/skyterra/y-crdt"

	"github.com/alkem-io/collaboration-service/internal/domain/service"
)

// SeedCorpus is a small, representative legacy corpus for the dry-run smoke test
// (SC-003/007/009 on a fake corpus) — it exercises every path the driver branches
// on WITHOUT needing the server read-path or a live store:
//
//   - a non-trivial memo (real Yjs v2 update, base64) → migrated
//   - a memo with a real Yjs *v1* update → migrated (v1→v2 fallback path)
//   - an empty/never-edited memo → skipped
//   - a corrupt memo (undecodable base64-of-garbage) → flagged
//   - a source-flagged record → flagged (carried through)
//   - an unknown content type → flagged
//   - a whiteboard with real Excalidraw JSON → flagged in build-ahead (no Node
//     seam) / migrated once the binding is installed
//   - an empty whiteboard → skipped
//
// The memo updates are generated by the SAME y-crdt core the service runs, so the
// seed proves the Go memo path end to end (decode→re-encode→round-trip→validate).
func SeedCorpus() []LegacyRecord {
	return []LegacyRecord{
		{
			ID:                    "seed-memo-v2",
			ContentType:           "memo",
			Content:               seedMemoUpdateV2("Hello from a legacy memo (v2)."),
			AuthorizationPolicyID: "policy-memo-1",
		},
		{
			ID:                    "seed-memo-v1",
			ContentType:           "memo",
			Content:               seedMemoUpdateV1("Hello from a legacy memo (v1)."),
			AuthorizationPolicyID: "policy-memo-2",
		},
		{
			ID:          "seed-memo-empty",
			ContentType: "memo",
			Content:     "", // never edited
		},
		{
			ID:          "seed-memo-corrupt",
			ContentType: "memo",
			// Valid base64, but the bytes are not a Yjs update of either version.
			Content: base64.StdEncoding.EncodeToString([]byte("not-a-yjs-update-at-all-just-bytes")),
		},
		{
			ID:          "seed-source-flagged",
			ContentType: "whiteboard",
			Flagged:     true,
			FlagReason:  "decompression_failed: simulated",
		},
		{
			ID:          "seed-unknown-type",
			ContentType: "spreadsheet",
			Content:     "irrelevant",
		},
		{
			ID:                    "seed-whiteboard",
			ContentType:           "whiteboard",
			Content:               seedExcalidrawJSON(),
			AuthorizationPolicyID: "policy-wb-1",
		},
		{
			ID:          "seed-whiteboard-empty",
			ContentType: "whiteboard",
			Content:     "",
		},
	}
}

// seedMemoUpdateV2 builds a real memo Y.Doc (root Y.XmlFragment "default" with a
// text node) and returns base64(EncodeStateAsUpdateV2) — what a v2-persisting
// legacy client would have stored.
func seedMemoUpdateV2(text string) string {
	doc := service.NewMigrationDoc("seed-memo-v2")
	frag := doc.GetXmlFragment("default").(*ycrdt.YXmlFragment)
	xt := ycrdt.NewYXmlText()
	frag.Push(ycrdt.ArrayAny{xt})
	xt.Insert(0, text, nil)
	return base64.StdEncoding.EncodeToString(ycrdt.EncodeStateAsUpdateV2(doc, nil))
}

// seedMemoUpdateV1 is seedMemoUpdateV2's v1 sibling — proving the converter's
// v1→v2 fallback path on a real v1-encoded update.
func seedMemoUpdateV1(text string) string {
	doc := service.NewMigrationDoc("seed-memo-v1")
	frag := doc.GetXmlFragment("default").(*ycrdt.YXmlFragment)
	xt := ycrdt.NewYXmlText()
	frag.Push(ycrdt.ArrayAny{xt})
	xt.Insert(0, text, nil)
	return base64.StdEncoding.EncodeToString(ycrdt.EncodeStateAsUpdate(doc, nil))
}

// seedExcalidrawJSON is a minimal but realistic Excalidraw scene the Node binding
// step would convert (two elements + appState + empty files). It is only consumed
// by the whiteboard converter (which flags it in build-ahead absent the Node
// seam), so its exact shape just has to be the {elements,appState,files} the
// binding's populateYDoc expects.
func seedExcalidrawJSON() string {
	scene := map[string]any{
		"elements": []map[string]any{
			{
				"id": "el-1", "type": "rectangle", "x": 10, "y": 20,
				"width": 100, "height": 50, "index": "a0", "isDeleted": false,
				"version": 1, "versionNonce": 12345, "strokeColor": "#000000",
			},
			{
				"id": "el-2", "type": "ellipse", "x": 200, "y": 80,
				"width": 60, "height": 60, "index": "a1", "isDeleted": false,
				"version": 1, "versionNonce": 67890, "strokeColor": "#ff0000",
			},
		},
		"appState": map[string]any{"viewBackgroundColor": "#ffffff", "name": "seed"},
		"files":    map[string]any{},
	}
	b, _ := json.Marshal(scene)
	return string(b)
}
